### PR TITLE
Added missing import of ReflectionClass

### PR DESCRIPTION
**Pull request by holtkamp**
as used here https://github.com/pheryjs/phery/blob/04ec73911b2250f8f5486eae5a83669ceeacd5c1/src/Phery/PheryResponse.php#L1475

### CODE REVIEW

**Comment by pocesar** [comment]
thanks!

**Comment by pocesar** [comment]
@holtkamp are you using phery 3.0.0-alpha1 in production? if so, do you think it's ok to make it 3.0.0-RC1?

**Comment by holtkamp** [comment]
@pocesar yeah, been using it for a while now, so tagging it as ```3.0.0-RC1``` sounds like a plan 👍

**Comment by holtkamp** [comment]
@pocesar any updates on this idea? Should we open a separate issue to get a stable version out for this library?

**Comment by pocesar** [comment]
@holtkamp I've been using 3.0.0-alpha5 in production without any problems, I just forgot to update this haha

**Comment by holtkamp** [comment]
😂 ok, will update to that one as well

**Pull request merged**
