### PR TITLE
PSR-4 support

### PR DESCRIPTION
**Pull request by holtkamp**
Initial approach, might be a 3.0.0-alpha1

### CODE REVIEW

**Comment by pocesar** [comment]
looks good to far! thanks for the hard work. just enlighten me the need to use `use ArrayObject;`, isn't it a global available class?

**Comment by holtkamp** [comment]
that class does not 'live' in the ```Phery``` namespace, so it either needs to be:

- 'imported' using ```use ArrayObject;```, after which it can be referred to as ```ArrayObject```
- referred to as ```\ArrayObject``` (note the prepended slash)

**Comment by pocesar** [comment]
ah makes sense

**Comment by pocesar** [comment]
merged in 3.0.0-alpha.1 branch, work it from there :+1:

**Comment by holtkamp** [comment]
Great. 

One thing I noticed when trying to use this branch is that I needed to change:

 ```phery/phery: "~2.7"```

to 

 ```phery/phery.js: "dev-3.0.0-alpha.1"```

Note the difference in the name. Maybe [packagist.org](https://packagist.org/packages/phery/phery) needs to be updated *and* use the [replace](https://getcomposer.org/doc/04-schema.md#replace) entry of composer.json in the new branch:

```"replace": {"phery/phery": "self.version"}```

**Comment by pocesar** [comment]
I think maybe it's because I didn't create a tag, but a branch?

**Pull request closed without merging**
